name: personal_torrent
description: "Flutter iOS torrent client (personal use) with pure-Dart engine"
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  # محرك تورنت (ملف .torrent فقط):
  dtorrent_task: ^0.4.0
  dtorrent_parser: ^1.0.8
  dtorrent_common: ^1.0.7
  # اختيار ملف .torrent + مسارات + مشاركة:
  file_picker: ^8.0.5
  path_provider: ^2.1.3
  share_plus: ^10.0.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
